name: Maven Build and Package (Java 21)

on:
  push:
    branches: [ main, master ] # Adjust branches as needed, e.g., 'main' or 'master'
  pull_request:
    branches: [ main, master ] # Adjust branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' # Changed from '17' to '21'
        distribution: 'temurin' # Recommended distribution for stability

    - name: Build with Maven
      run: mvn -B package --file pom.xml
